simple_pipe: simple_pipe.c
	$(CC) $(FLAGS) $^ -o simple_pipe

dup_example: dup_example.c
	$(CC) $(FLAGS) $^ -o dup_example

zad3: zad3.c
	$(CC) $(FLAGS) $^ -o zad3
clean:
	rm -f *.o
	rm -f *~
	rm -f *.bak